In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.datasets import load_breast_cancer

In [3]:
data = load_breast_cancer()
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [4]:
data.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [5]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

In [6]:
x= data.data
y = data.target
df = pd.DataFrame(x,columns=data.feature_names)
df['target'] = y

In [7]:
df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,1

In [8]:
df['target'].value_counts(normalize = True)

target
1    0.627417
0    0.372583
Name: proportion, dtype: float64

In [9]:
# To handle imbalenced data apply all the methods only on the training data
from sklearn.model_selection import train_test_split

In [10]:
X_train,X_test,y_train,y_test = train_test_split(x,y,random_state=42,test_size=0.2,stratify=y)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((455, 30), (114, 30), (455,), (114,))

In [11]:
pd.Series(y_train).value_counts(normalize=True)

1    0.626374
0    0.373626
Name: proportion, dtype: float64

In [12]:
pd.Series(y_train).value_counts()

1    285
0    170
Name: count, dtype: int64

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
ss = StandardScaler()
ss

StandardScaler()

In [15]:
X_train_transformed = ss.fit_transform(X_train)
X_train_transformed

array([[-1.07200079, -0.6584246 , -1.0880801 , ..., -1.35052668,
        -0.35265805, -0.54138003],
       [ 1.74874285,  0.06650173,  1.75115682, ...,  1.54991557,
         0.19107787, -0.1737386 ],
       [-0.97473376, -0.93112416, -0.99770871, ..., -1.70744192,
        -0.307734  , -1.21303263],
       ...,
       [ 0.39844772,  1.06867262,  0.50751384, ...,  1.53492543,
         0.16164487,  1.23754763],
       [ 0.85331409, -0.0380331 ,  0.9054796 , ...,  2.10455077,
         0.31035897,  0.36249578],
       [-0.91179628, -0.82431683, -0.87666079, ..., -0.51332734,
        -0.50756857,  1.30824791]])

In [16]:
from imblearn.over_sampling import SMOTE

In [17]:
smote = SMOTE(k_neighbors=5,sampling_strategy='auto')

In [18]:
X_train_res,y_train_res = smote.fit_resample(X_train_transformed,y_train)
X_train_res.shape,y_train_res.shape

((570, 30), (570,))

In [19]:
pd.Series(y_train_res).value_counts()

1    285
0    285
Name: count, dtype: int64

In [20]:
smote = SMOTE(k_neighbors=5,sampling_strategy={1:285,0:260})

In [21]:
X_train_res,y_train_res = smote.fit_resample(X_train_transformed,y_train)
X_train_res.shape,y_train_res.shape

((545, 30), (545,))

In [22]:
pd.Series(y_train_res).value_counts()

1    285
0    260
Name: count, dtype: int64

---

In [23]:
X_train_transformed = pd.DataFrame(X_train_res,columns=ss.get_feature_names_out())
X_train_transformed

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x20,x21,x22,x23,x24,x25,x26,x27,x28,x29
0,-1.072001,-0.658425,-1.088080,-0.939274,-0.135940,-1.008718,-0.968359,-1.102032,0.281062,-0.113231,...,-1.034094,-0.623497,-1.070773,-0.876534,-0.169982,-1.038836,-1.078995,-1.350527,-0.352658,-0.541380
1,1.748743,0.066502,1.751157,1.745559,1.274468,0.842288,1.519852,1.994664,-0.293045,-0.320180,...,1.228342,-0.092833,1.187467,1.104386,1.517001,0.249655,1.178594,1.549916,0.191078,-0.173739
2,-0.974734,-0.931124,-0.997709,-0.867589,-0.613515,-1.138154,-1.092292,-1.243358,0.434395,-0.429247,...,-0.973231,-1.036772,-1.008044,-0.834168,-1.097823,-1.167260,-1.282241,-1.707442,-0.307734,-1.213033
3,-0.145103,-1.215186,-0.123013,-0.253192,0.664482,0.286762,-0.129729,-0.098605,0.555635,0.029395,...,-0.251266,-1.369643,-0.166633,-0.330292,0.234006,0.096874,-0.087521,-0.344838,0.242198,-0.118266
4,-0.771617,-0.081211,-0.803700,-0.732927,-0.672282,-1.006099,-0.798502,-0.684484,0.737495,-0.457213,...,-0.801135,0.079230,-0.824381,-0.741830,-0.911367,-0.984612,-0.933190,-0.777604,0.555118,-0.761639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1.510403,-0.173561,1.523167,1.470581,1.136746,1.042936,1.413824,1.644547,0.062290,-0.323225,...,1.318625,-0.421198,1.263008,1.191145,1.550844,0.982027,1.692830,1.717248,0.838065,0.154977
541,1.178099,-0.578448,1.146474,1.108836,0.307105,0.421449,0.529418,1.013644,-0.017765,0.326536,...,1.188993,-0.623954,1.084664,1.099791,0.162981,0.284254,0.195385,0.682648,-0.491341,0.296465
542,-0.582526,0.721044,-0.452046,-0.604168,1.738107,2.398071,1.468959,0.779830,0.982140,2.614724,...,-0.348887,2.024424,-0.325901,-0.399823,2.808447,4.798399,3.458980,1.751711,2.155486,5.583352
543,0.856672,0.519768,0.836990,0.786870,1.086783,0.041159,0.701126,1.233256,-0.261890,-0.269486,...,1.046012,1.225219,1.126355,0.937562,0.616353,-0.285712,0.483484,0.995816,-0.390396,-0.363545
544,0.375307,-0.060346,0.364022,0.227150,1.522516,0.484644,0.896719,0.920478,0.435016,0.052482,...,0.441609,-0.479060,0.369511,0.187606,0.411199,-0.247335,0.271496,0.486978,0.438795,-0.534844

In [24]:
X_train_transformed['x28'] = X_train_transformed['x28'].apply(lambda x:'high' if x>0 else 'low')
X_train_transformed['x28']

0       low
1      high
2       low
3      high
4      high
       ...
540    high
541     low
542    high
543     low
544    high
Name: x28, Length: 545, dtype: object

In [25]:
X_train_transformed['x29'] = X_train_transformed['x29'].apply(lambda x:'yes' if x>0 else 'no')
X_train_transformed['x29']

0       no
1       no
2       no
3       no
4       no
      ...
540    yes
541    yes
542    yes
543     no
544     no
Name: x29, Length: 545, dtype: object

In [26]:
X_train_transformed.head()

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x20,x21,x22,x23,x24,x25,x26,x27,x28,x29
0,-1.072001,-0.658425,-1.088080,-0.939274,-0.135940,-1.008718,-0.968359,-1.102032,0.281062,-0.113231,...,-1.034094,-0.623497,-1.070773,-0.876534,-0.169982,-1.038836,-1.078995,-1.350527,low,no
1,1.748743,0.066502,1.751157,1.745559,1.274468,0.842288,1.519852,1.994664,-0.293045,-0.320180,...,1.228342,-0.092833,1.187467,1.104386,1.517001,0.249655,1.178594,1.549916,high,no
2,-0.974734,-0.931124,-0.997709,-0.867589,-0.613515,-1.138154,-1.092292,-1.243358,0.434395,-0.429247,...,-0.973231,-1.036772,-1.008044,-0.834168,-1.097823,-1.167260,-1.282241,-1.707442,low,no
3,-0.145103,-1.215186,-0.123013,-0.253192,0.664482,0.286762,-0.129729,-0.098605,0.555635,0.029395,...,-0.251266,-1.369643,-0.166633,-0.330292,0.234006,0.096874,-0.087521,-0.344838,high,no
4,-0.771617,-0.081211,-0.803700,-0.732927,-0.672282,-1.006099,-0.798502,-0.684484,0.737495,-0.457213,...,-0.801135,0.079230,-0.824381,-0.741830,-0.911367,-0.984612,-0.933190,-0.777604,high,no

In [27]:
from imblearn.over_sampling import SMOTENC

In [28]:
smotenc = SMOTENC(categorical_features=['x28','x29'])
smotenc

SMOTENC(categorical_features=['x28', 'x29'])

In [29]:
X_train_res,y_train_res = smotenc.fit_resample(X_train_transformed,y_train)
X_train_res.shape,y_train_res.shape

((660, 30), (570,))

In [30]:
X_train_res

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x20,x21,x22,x23,x24,x25,x26,x27,x28,x29
0,-1.072001,-0.658425,-1.088080,-0.939274,-0.135940,-1.008718,-0.968359,-1.102032,0.281062,-0.113231,...,-1.034094,-0.623497,-1.070773,-0.876534,-0.169982,-1.038836,-1.078995,-1.350527,low,no
1,1.748743,0.066502,1.751157,1.745559,1.274468,0.842288,1.519852,1.994664,-0.293045,-0.320180,...,1.228342,-0.092833,1.187467,1.104386,1.517001,0.249655,1.178594,1.549916,high,no
2,-0.974734,-0.931124,-0.997709,-0.867589,-0.613515,-1.138154,-1.092292,-1.243358,0.434395,-0.429247,...,-0.973231,-1.036772,-1.008044,-0.834168,-1.097823,-1.167260,-1.282241,-1.707442,low,no
3,-0.145103,-1.215186,-0.123013,-0.253192,0.664482,0.286762,-0.129729,-0.098605,0.555635,0.029395,...,-0.251266,-1.369643,-0.166633,-0.330292,0.234006,0.096874,-0.087521,-0.344838,high,no
4,-0.771617,-0.081211,-0.803700,-0.732927,-0.672282,-1.006099,-0.798502,-0.684484,0.737495,-0.457213,...,-0.801135,0.079230,-0.824381,-0.741830,-0.911367,-0.984612,-0.933190,-0.777604,high,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,2.005903,0.295973,1.928898,2.126773,0.085900,0.291241,0.864028,1.723571,-0.855892,-0.835874,...,1.978585,1.024106,1.850742,2.067897,0.216114,0.362056,0.772128,1.699958,high,yes
656,0.598459,-0.257143,0.659940,0.458846,0.633901,1.093652,0.758606,0.838969,0.568738,0.388449,...,0.754062,0.166875,0.740018,0.599349,0.449486,1.859530,1.132368,1.034292,high,yes
657,1.752353,1.960431,1.683279,1.827454,0.108226,0.104056,0.699002,1.052651,-0.179251,-1.047262,...,1.823804,2.324187,1.760283,1.937706,0.806002,0.360083,0.488351,0.820143,low,no
658,-0.348539,0.698567,-0.255623,-0.417376,0.936990,1.423523,0.979895,0.526557,1.134706,1.354198,...,-0.199614,0.729377,-0.034404,-0.291438,2.002145,1.761824,1.626432,1.267820,high,yes
659,1.554927,0.226169,1.561144,1.545681,0.752329,1.512458,1.787815,1.220139,-0.198749,0.553921,...,1.873444,0.109786,1.581414,1.885350,1.666878,2.217262,2.573171,1.968636,high,yes

---

- SMOTEN

In [31]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data"
columns = [
   "buying", "maint", "doors",
   "persons", "lug_boot", "safety", "target"
]


df = pd.read_csv(url, names=columns)


df.head()

  buying  maint doors persons lug_boot safety target
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [32]:
df['target'].value_counts()

target
unacc    1210
acc       384
good       69
vgood      65
Name: count, dtype: int64

In [37]:
from imblearn.over_sampling import SMOTENC

In [38]:
smoten = SMOTENC(sampling_strategy={'unacc':1210,'acc':600,'good':300,'vgood':'300'})
smoten

TypeError: SMOTENC.__init__() missing 1 required positional argument: 'categorical_features'

In [35]:
X = df.drop('target',axis=1)
y = df['target']
X.shape,y.shape

((1728, 6), (1728,))

In [ ]:
X_res, y_res = smoten.fit_resample(X,y)

----

In [40]:
from sklearn.datasets import load_breast_cancer

In [43]:
data = load_breast_cancer()
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [44]:
X = data.data
y = data.target
X.shape,y.shape

((569, 30), (569,))

In [46]:
df = pd.DataFrame(X,columns=data.feature_names)
df['target'] = y

In [47]:
df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,1

In [48]:
df.shape

(569, 31)

In [49]:
df['target'].value_counts(normalize=True)

target
1    0.627417
0    0.372583
Name: proportion, dtype: float64

In [50]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42,test_size=0.2,stratify=y)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((455, 30), (114, 30), (455,), (114,))

In [52]:
# apply imbalanced data handling procedures on train data
pd.Series(y_train).value_counts()

1    285
0    170
Name: count, dtype: int64

- ADASYN

In [57]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler().set_output(transform = 'pandas')
mms

MinMaxScaler()

In [58]:
X_train_transformed = mms.fit_transform(X_train)
X_train_transformed

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x20,x21,x22,x23,x24,x25,x26,x27,x28,x29
0,0.158029,0.224552,0.148711,0.077011,0.387273,0.093737,0.023711,0.027311,0.416667,0.253791,...,0.131746,0.259861,0.115769,0.061507,0.389391,0.059309,0.035016,0.081821,0.219988,0.124295
1,0.624686,0.332432,0.622003,0.469752,0.617958,0.397276,0.499766,0.625746,0.335354,0.222620,...,0.559524,0.347814,0.534351,0.398485,0.647490,0.258957,0.423962,0.746735,0.289178,0.168634
2,0.174121,0.183970,0.163776,0.087497,0.309162,0.072511,0.000000,0.000000,0.438384,0.206192,...,0.143254,0.191365,0.127397,0.068714,0.247436,0.039410,0.000000,0.000000,0.225705,0.043290
3,0.311373,0.141698,0.309585,0.177372,0.518190,0.306178,0.184161,0.221223,0.455556,0.275274,...,0.279762,0.136194,0.283358,0.154429,0.451199,0.235284,0.205831,0.312371,0.295683,0.175325
4,0.207724,0.310450,0.196116,0.107196,0.299550,0.094166,0.056209,0.108002,0.481313,0.201980,...,0.175794,0.376333,0.161440,0.084422,0.275963,0.067711,0.060136,0.213162,0.335502,0.097731
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450,0.392778,0.429489,0.380969,0.240756,0.341404,0.263235,0.125937,0.162177,0.336869,0.278222,...,0.391667,0.426706,0.354352,0.242670,0.400258,0.293594,0.289936,0.421306,0.317366,0.279942
451,0.593923,0.310788,0.592288,0.455742,0.638642,0.444206,0.514761,0.527833,0.369697,0.327717,...,0.714286,0.378998,0.674660,0.575274,0.532025,0.372859,0.488898,0.680412,0.276562,0.290240
452,0.401297,0.481569,0.414691,0.249544,0.678793,0.514140,0.475633,0.423459,0.377273,0.439553,...,0.364286,0.647921,0.376153,0.223050,0.692997,0.455424,0.472125,0.743299,0.285433,0.338843
453,0.476549,0.316875,0.481031,0.319041,0.627692,0.422735,0.447516,0.541750,0.540909,0.279907,...,0.462698,0.343017,0.464475,0.309166,0.673300,0.355202,0.400799,0.873883,0.304356,0.233307
454,0.184533,0.199865,0.183954,0.091446,0.464655,0.268450,0.119845,0.078082,0.404545,0.387742,...,0.159127,0.195362,0.169769,0.076352,0.421314,0.351709,0.268770,0.273746,0.200276,0.347370

In [53]:
from imblearn.over_sampling import ADASYN

In [54]:
adasyn = ADASYN()
adasyn

ADASYN()

In [60]:
X_train_res , y_train_res = adasyn.fit_resample(X_train_transformed,y_train)
X_train_res.shape , y_train_res.shape

((574, 30), (574,))

In [62]:
pd.Series(y_train_res).value_counts() #289 is due to floating point error

0    289
1    285
Name: count, dtype: int64

### Under Sampling

In [63]:
# Random under sampling
from imblearn.under_sampling import RandomUnderSampler

In [64]:
rus = RandomUnderSampler()
rus

RandomUnderSampler()

In [65]:
pd.Series(y_train).value_counts()

1    285
0    170
Name: count, dtype: int64

In [66]:
X_train_res,y_train_res = rus.fit_resample(X_train_transformed,y_train)
X_train_res.shape,y_train_res.shape

((340, 30), (340,))

In [67]:
pd.Series(y_train_res).value_counts()

0    170
1    170
Name: count, dtype: int64

In [68]:
# TOMEKLINKS
from imblearn.under_sampling import TomekLinks

In [69]:
tl = TomekLinks()
tl

TomekLinks()

In [71]:
pd.Series(y_train).value_counts()

1    285
0    170
Name: count, dtype: int64

In [72]:
X_train_res , y_train_res = tl.fit_resample(X_train_transformed,y_train)
X_train_res.shape,y_train_res.shape

((450, 30), (450,))

In [73]:
pd.Series(y_train_res).value_counts()

1    280
0    170
Name: count, dtype: int64

In [74]:
tl = TomekLinks(sampling_strategy='all')
tl

TomekLinks(sampling_strategy='all')

In [75]:
X_train_res , y_train_res = tl.fit_resample(X_train_transformed,y_train)
X_train_res.shape,y_train_res.shape

((445, 30), (445,))

In [76]:
pd.Series(y_train_res).value_counts()

1    280
0    165
Name: count, dtype: int64

In [77]:
### Condensed Nearest Neighbours
from imblearn.under_sampling import CondensedNearestNeighbour
cnn = CondensedNearestNeighbour()

In [78]:
pd.Series(y_train).value_counts()

1    285
0    170
Name: count, dtype: int64

In [79]:
X_train_res , y_train_res = cnn.fit_resample(X_train_transformed,y_train)
X_train_res.shape,y_train_res.shape

((209, 30), (209,))

In [80]:
pd.Series(y_train_res).value_counts()

0    170
1     39
Name: count, dtype: int64